### ISSUE TITLE
Date sometimes not recognized in v3.9.1

### ISSUE THREAD

**Issue by mcstafford-git** [DanielJDufour/date-extractor#12]
>>> extract_date("some_text_20140205") or print("Uhoh...")
    datetime.datetime(2014, 2, 5, 0, 0, tzinfo=<UTC>)

    >>> extract_date("some_text20140205") or print("Uhoh...")
    Uhoh...

**Comment by DanielJDufour** [comment]
Good catch!  I'll fix this! Might take a few days though.  Open to a PR if you'd like to do it :-)

**Comment by DanielJDufour** [comment]
Fixed!
