### ISSUE TITLE
UnicodeDecodeError on Import

### ISSUE THREAD

**Issue by NOVOMOTUS** [DanielJDufour/date-extractor#5]
Getting this error during import, running Python 3.6.3:
```
File "myproject\myfile.py", line 6, in <module>
    from date_extractor import extract_dates
  File "myproject\venv\lib\site-packages\date_extractor\__init__.py", line 6, in <module>
    from . import enumerations
  File "myproject\venv\lib\site-packages\date_extractor\enumerations.py", line 83, in <module>
    lines = f.read().split("\n")
  File "myproject\venv\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 129: character maps to <undefined>
```

Works fine on another machine running 3.5.?. Any clues?

**Comment by DanielJDufour** [comment]
Thanks for catching that! I might have to pass in the encoding when opening the file for newer versions of Python.  I'll take a deeper look as soon as I can. Expect a fix within 24hrs.

**Comment by DanielJDufour** [comment]
This should be fixed now.  It would be a great help if you could check and let me know! Thanks and have a good weekend.

**Comment by NOVOMOTUS** [comment]
Working now!

**Comment by DanielJDufour** [comment]
Great. I'll close this issue, but feel free to open another issue if you find another bug!
